require('jquery');
require('./plugin/jquery.inputmask.bundle.min');
require('./plugin/jquery.validate.min');
//require('./plugin/slick');
require('./plugin/svg');
// require('./plugin/svg.pathmorphing.js');
require('./plugin/ion.rangeSlider.min');
require('./plugin/animatescroll.min');
require('./popups.js');
require('./forms.js');
require('./script.js');
